### ISSUE TITLE
3.8.2.10 available

### ISSUE THREAD

**Issue by cam1170** [brogers5/chocolatey-package-wd-dashboard#1]
According to their release notes 3.8.2.10 is available. The installer doesn't give a version and I haven't tried installing it myself though.
https://wddashboarddownloads.wdc.com/wdDashboard/WesternDigitalDashboardReleaseNotes.pdf
https://wddashboarddownloads.wdc.com/wdDashboard/DashboardSetup.exe

**Comment by brogers5** [comment]
Thanks for the report.

The Chocolatey package consumes Western Digital's "Standalone Installer" package (for offline installs) instead of the web installer you've linked to. For some reason, Western Digital hasn't published an updated package, so that's why the Chocolatey package is a version behind.

The update script actually queries the same endpoint used by the software to check for updates, so I currently have it effectively cancelling the update process if the newly downloaded package's checksum is identical to the previous version's.

I have an open support ticket to get clarification as to whether they intend to update it. If I don't hear back soon, I'll look into migrating to the web installer package.

**Comment by brogers5** [comment]
Circling back to this - after some back and forth with a tier 1 agent, the ticket was escalated to a tier 2 agent, who then proceeded to ignore my communication preference for emails and insisted I get on the phone with them. After a few failed attempts to get connected, life happened and this ended up slipping through the cracks. Apologies for the delay.

Western Digital, however, just recently released v4.0.2.19. and updated the standalone installer package accordingly. I will move forward with pushing a package for that instead, since 3.8.2.10 is no longer available for download.
